# Generated by Django 4.1.5 on 2023-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=150)),
                ('a', models.CharField(max_length=150)),
                ('a_status', models.CharField(default=0, max_length=2)),
                ('b', models.CharField(max_length=150)),
                ('b_status', models.CharField(default=0, max_length=2)),
                ('c', models.CharField(max_length=150)),
                ('c_status', models.CharField(default=0, max_length=2)),
                ('d', models.CharField(max_length=150)),
                ('d_status', models.CharField(default=0, max_length=2)),
                ('e', models.CharField(max_length=150)),
                ('e_status', models.CharField(default=0, max_length=2)),
                ('f', models.CharField(max_length=150)),
                ('f_status', models.CharField(default=0, max_length=2)),
                ('g', models.CharField(max_length=150)),
                ('g_status', models.CharField(default=0, max_length=2)),
                ('h', models.CharField(max_length=150)),
                ('h_status', models.CharField(default=0, max_length=2)),
                ('j', models.CharField(max_length=150)),
                ('j_status', models.CharField(default=0, max_length=2)),
                ('k', models.CharField(max_length=150)),
                ('k_status', models.CharField(default=0, max_length=2)),
                ('l', models.CharField(max_length=150)),
                ('l_status', models.CharField(default=0, max_length=2)),
            ],
        ),
    ]
